CREATE TABLE IF NOT EXISTS bee_family (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  type varchar,
  power varchar
);

CREATE TABLE IF NOT EXISTS hive (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  material varchar,
  type varchar,
  frames_per_body varchar
);
